org: flanche
service: chinawok-usuarios

provider:
  name: aws
  runtime: python3.12
  memorySize: 512
  timeout: 300
  region: us-east-1
  
  environment:
    TABLE_USUARIOS: ${env:TABLE_USUARIOS, 'ChinaWok-Usuarios'}
    TABLE_TOKENS: ${env:TABLE_TOKENS, 'ChinaWok-Tokens'}

  iam:
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/LabRole

functions:
  crear:
    handler: personas/Crear_usuario_ChinaWok.lambda_handler
    events:
      - http:
          path: usuario/crear
          method: post
          cors: true

  login:
    handler: personas/Login_usuario_ChinaWok.lambda_handler
    events:
      - http:
          path: usuario/login
          method: post
          cors: true

  listar:
    handler: personas/Listar_usuario_ChinaWok.lambda_handler
    events:
      - http:
          path: usuario/listar
          method: get
          cors: true

  buscar:
    handler: personas/Buscar_usuario_correo_ChinaWok.lambda_handler
    events:
      - http:
          path: usuario/buscar
          method: post
          cors: true

  modificar:
    handler: personas/Modificar_Usuario_ChinaWok.lambda_handler
    events:
      - http:
          path: usuario/modificar
          method: put
          cors: true

  eliminar:
    handler: personas/Eliminar_usuario_ChinaWok.lambda_handler
    events:
      - http:
          path: usuario/eliminar
          method: delete
          cors: true

  validarToken:
    handler: personas/Validar_Token_Acceso_ChinaWok.lambda_handler
    events:
      - http:
          path: usuario/validartoken
          method: post
          cors: true
